kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 80 # ให้ ingress controller ใน cluster ฟังบน port 80
    hostPort: 80 # map ออกมาที่ localhost:80
    # protocol: TCP
  - containerPort: 443 # ให้ ingress controller ใน cluster ฟังบน port 443
    hostPort: 443 # map ออกมาที่ localhost:443
    # protocol: TCP

