replicas: 1

logstashConfig:
  logstash.yml: |
    http.host: "0.0.0.0"
    xpack.monitoring.elasticsearch.hosts: [ "http://elasticsearch-master:9200" ]

logstashPipeline:
  logstash.conf: |
    input {
      beats {
        port => 5044
      }
    }
    filter {
      if [fields][service] {
        mutate {
          add_field => { "service" => "%{[fields][service]}" }
        }
      }
    }
    output {
      elasticsearch {
        hosts => [ "elasticsearch-master:9200" ]
        index => "logstash-%{+YYYY.MM.dd}"
      }
    }

resources:
  requests:
    cpu: "100m"
    memory: "512Mi"
  limits:
    cpu: "1000m"
    memory: "1Gi"
