apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: elasticsearch-ingress
  namespace: logging
  # annotations:
  #   nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: png.com
    http:
      paths:
      - path: /elas
        pathType: Prefix
        backend:
          service:
            name: elasticsearch-master
            port:
              number: 9200
  ingressClassName: nginx
